# SPDX-FileCopyrightText: Copyright (c) 2009-2025 Zerocracy
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
]

[default.extend-identifiers]
"nam" = "nam"
"shll" = "shll"
"scrpt" = "scrpt"
"MIIEowIBAAKCAQEAzDKK1b2dXgXepTvgpy2klfTZ6BVZCwg09eoyOtAWUnX64xQs" = "MIIEowIBAAKCAQEAzDKK1b2dXgXepTvgpy2klfTZ6BVZCwg09eoyOtAWUnX64xQs"
"KgDKCNskCGoV0TAjYzdGfiABX17HcGePaL8GaItzWkakpWFoJGAXOGTmiKHqd49o" = "KgDKCNskCGoV0TAjYzdGfiABX17HcGePaL8GaItzWkakpWFoJGAXOGTmiKHqd49o"
"OtGng5zHLx5cV+BrbpFt1m2ja4BjacYMU" = "OtGng5zHLx5cV+BrbpFt1m2ja4BjacYMU"
