# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".pdd",
    "**.json",
    "**.md",
    "**.pdf",
    "**.png",
    "**.svg",
    "**.txt",
    "**.vm",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CNAME",
    "**/MANIFEST.MF",
    "**/Procfile",
    "CNAME",
    "MANIFEST.MF",
    "Procfile",
    "README.md",
    "renovate.json",
    "src/jekyll/favicon.ico",
    "src/main/resources/com/rultor/agents/daemons/secring.gpg.asc",
    "src/main/resources/com/rultor/agents/rultor.key",
    "src/main/resources/META-INF/services/javax.xml.transform.TransformerFactory",
    "src/main/resources/META-INF/services/javax.xml.xpath.XPathFactory",
    "src/test/resources/com/rultor/agents/rultor.key",
    "src/test/resources/com/rultor/agents/shells/authorized_keys",
    "src/test/resources/com/rultor/agents/shells/id_rsa",
    "src/test/resources/com/rultor/agents/shells/private.key",
    "src/test/resources/com/rultor/agents/shells/ssh_host_rsa_key",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
